services:
  - type: web
    name: kaisertech
    runtime: static
    repo: https://github.com/Padilha1/kaisertech.git
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeployTrigger: checksPass
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
